[pytest]
# 注册并启用 pytest-embedded 的服务
addopts = --embedded-services serial
# 配置控制台实时输出的日志级别 (根据需要调整为 DEBUG 或 WARN)
log_cli = true
log_cli_level = INFO
# 配置日志日期格式
log_date_format = %Y-%m-%d %H:%M:%S

markers =
    serial: mark test as requiring a serial device
    stress: mark test as a stress test